---

run:
  timeout: 3m
  skip-dirs:
    - vendor

output:
  format: colored-line-number
  sort-results: true
  print-issued-lines: false

linters:
  disable-all: true
  fast: false
  enable:
    - bodyclose
    - deadcode
    - errcheck
    - exhaustive
    - gochecknoinits
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
